### ISSUE TITLE
error in line 80

### ISSUE THREAD

**Issue by Deyelk** [avramit/instahack#1]
2 Passwords loads successfully
Please enter a username: matthew
Traceback (most recent call last):
  File "hackinsta.py", line 80, in <module>
    username = str(input('Please enter a username: '))
  File "<string>", line 1, in <module>
NameError: name 'matthew' is not defined
(jessie)deyelk@localhost:/var/host/media/removable/UNTITLED/instahack-master$ 

note im running linux with python 2.7

**Comment by avramit** [comment]
@Deyelk please try to run on python 3

**Comment by Deyelk** [comment]
Will do

**Comment by Deyelk** [comment]
Same error

**Comment by Deyelk** [comment]
I found a fix changing it to raw input makes it work

**Comment by avramit** [comment]
@Deyelk please close to issue

**Comment by arshiay** [comment]
how fix this?

**Comment by avramit** [comment]
@arshiay it's not a bug, that happens when you try to run the script on Python 2.7 and not Python 3.
If you want to run the script on Python 2.7 change input to raw_input
