### ISSUE TITLE
Cant use proxy (Proxy auth error) (Old version)

### ISSUE THREAD

**Issue by XVR1212** [avramit/Instahack#10]
getting this error 
![5cxznzozqw2drdbunzfgew](https://user-images.githubusercontent.com/30773996/30249920-886eeeb0-964e-11e7-8223-a21e358d6450.png)

the program work normaly if i choose ''n'' when it ask me if i want proxy
![fai4zz-aq3uzi9md1nt3tq](https://user-images.githubusercontent.com/30773996/30249964-83f7ea34-964f-11e7-82a4-5a35a8c053b2.png)

**Comment by deathsec** [comment]
Hey @XVR1212 check my project its way better than this , it mimics **Instagram Android App** and uses tor to jump from location to location , its easy to setup in linux  , it does not block your computer or anything , runs efficiently even with large password list , all you need is tor server up and running which is easy to do in linux , so i suggest you boot into kali linux and try my tool  , but i did not document how to on tor server , you have to refer kali linux documentation on how to restart and start tor server 

[Instagram-Py - Simple Instagram Brute Force Attack script](https://github.com/deathsec/Instagram-Py)

**Comment by PrestigeSyria** [comment]
deathsec how can i setup ur project..?

**Comment by deathsec** [comment]
@PrestigeSyria you need to install **tor server** (Not tor browser) and open the **control port** for **tor** and then refer README of my repo and follow the installation instructions ( **that is specific to linux users but you can google how to install a pip package in windows and get started** ) .

**Note** : you can **google** on **how to setup tor server and open tor control port in Linux/Windows/MacOSX**

I think i need to create a video instruction on how to!
