### ISSUE TITLE
PROBLEM : Can't find user named

### ISSUE THREAD

**Issue by HuhMe9** [avramit/Instahack#106]
C:\Users\HP\Desktop\Instahack-master>python hackinsta.py hadore553 passwords.txt
[*] Loading proxies
[*] Proxy: <Proxy CN 0.66s [HTTP: Transparent] 124.133.230.254:80>
[*] 965 passwords loaded successfully
[*] Can't find user named "hadore553"

please help me

**Comment by KemKore** [comment]
I have the same issue

**Comment by JellyWX** [comment]
Problem is already reported (14th April) with solution. Please close.

**Comment by HuhMe9** [comment]
Okay Thank You.
