### ISSUE TITLE
Fork Instagram-Py

### ISSUE THREAD

**Issue by deathsec** [avramit/instahack#11]
Hi @avramit  , no offense but your tool is good but not efficient as for the proxy you should use stem python library to control tor , so if you want to know how it is done fork my project , with my tool you can test infinite passwords efficiently!

[Instagram-Py - Simple Brute Force Attack Script!](https://github.com/deathsec/Instagram-Py)

**Comment by avramit** [comment]
@deathsec Cool tool, I am only 15 years old,i know they are better tools than mine...

**Comment by deathsec** [comment]
@avramit don't limit your skills to age , you have to be plus ultra , and i am just couple of years older than you! , like alan turing ( father of computational theory ).. Work hard and learn the standards and not online tutorials!
