### ISSUE TITLE
Can't find user named "username"

### ISSUE THREAD

**Issue by Epheandrill** [avramit/Instahack#112]
`[*] Loading proxies
[*] Proxy: <Proxy ES 0.17s [HTTP: High] 185.93.3.123:8080>
[*] 965 passwords loaded successfully
[*] Can't find user named "username"`

with a real user from instagram does not working, why ?
tks

edit: i use `python3 hackinsta.py username passwords.txt` for working program

**Comment by NRPC** [comment]
Got the same issue

**Comment by JellyWX** [comment]
Problem is already reported (14th April) with solution. Please close.

**Comment by Epheandrill** [comment]
Ok solution worked thanks. Push code please
