### ISSUE TITLE
Can't find username 

### ISSUE THREAD

**Issue by ram2141** [avramit/Instahack#124]
I don't know why I am getting this error?
it's a correct username. Please help me to solve this issue. I tried couple of usernames but it gives me same error for all the users... See attached screenshot.

![image](https://user-images.githubusercontent.com/31553388/43473797-f4ea6528-94a5-11e8-8f3e-b76a33294e2c.png)

**Comment by ColeShelly** [comment]
Same Problem..

**Comment by RemiKYS** [comment]
Same Plz Help.

**Comment by ColeShelly** [comment]
Fixed it

**Comment by ColeShelly** [comment]
#91

**Comment by ram2141** [comment]
Thanks @ColeShelly .
