### ISSUE TITLE
Help, not sure what i'm doing wrong (MemoryError - 360m passwords)

### ISSUE THREAD

**Issue by Megalax** [avramit/Instahack#15]
Traceback (most recent call last):
  File "hackinsta.py", line 142, in <module>
    instabrute = Instabrute(Input('Please enter a username: '))
  File "hackinsta.py", line 34, in __init__
    self.loadPasswords()
  File "hackinsta.py", line 48, in loadPasswords
    self.passwords = f.read().splitlines()
MemoryError

This happens everytime I type the username in

**Comment by avramit** [comment]
how many passwords in your list

**Comment by Megalax** [comment]
306 million

**Comment by avramit** [comment]
@Megalax thats crazy ! you cant use 306 million passwords ! instagram will block you

**Comment by Megalax** [comment]
lol alright then

**Comment by avramit** [comment]
Please close this issue
