### ISSUE TITLE
request timeout and blocking 

### ISSUE THREAD

**Issue by Deyelk** [avramit/instahack#2]
this has the username removed but i was try to run this through proxys so there went any blockages 
500 Passwords loads successfully
Please enter a username:
Please add delay between the passwords (in seconds): 1
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
К сожалению, слишком много запросов. Попробуйте еще раз позже.
^CTraceback (most recent call last):
  File "hackinsta.py", line 94, in <module>
    sess = Login(username,password)
  File "hackinsta.py", line 49, in Login
    r = sess.get('https://www.instagram.com/') 
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 194, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1320, in recv
    result = _lib.SSL_read(self._ssl, buf, bufsiz)
KeyboardInterrupt

**Comment by avramit** [comment]
@Deyelk i know about the blocking

**Comment by avramit** [comment]
@Deyelk you cant try 500 passwords in 8min

**Comment by Deyelk** [comment]
I mean I was hoping u could a to be fair I was changing proxys every 10 seconds

**Comment by avramit** [comment]
@Deyelk you edit the code?

**Comment by Deyelk** [comment]
Naw I was using tor-buddy

**Comment by Deyelk** [comment]
Tho I think there just blocking anything Russian

**Comment by Deyelk** [comment]
What's the fastest it'll go without being blocked

**Comment by avramit** [comment]
@Deyelk it's depends,  soon I will add proxy's server to change user IP every 5 passwords

**Comment by Deyelk** [comment]
Interesting should i be finding a proxy list or are u running it through tor

**Comment by avramit** [comment]
@Deyelk i add proxy support
