### ISSUE TITLE
Please help me fix this A.S.A.P

### ISSUE THREAD

**Issue by NAZSSYKO** [avramit/Instahack#28]
File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 128, in Login
    randomProxy() #Check that, may contain bugs
NameError: global name 'randomProxy' is not defined

**Comment by NAZSSYKO** [comment]
I press n on Proxy then it work normally but then it keep coming "do you want to use proxy " if i  press Y.  File "hackinsta.py", line 154, in 
sess = instabrute.Login(password)
File "hackinsta.py", line 128, in Login
randomProxy() #Check that, may contain bugs
NameError: global name 'randomProxy' is not defined this keep coming . soo help me

**Comment by g14m3** [comment]
I have the same problem

**Comment by NAZSSYKO** [comment]
So do you have a solution

**Comment by g14m3** [comment]
No, brudda')

**Comment by NAZSSYKO** [comment]
maybe can debug it with radare2?what your opinion

**Comment by g14m3** [comment]
maybe, maybe...Radar2 can debug python project?

**Comment by mostafa7734** [comment]
Bad

**Comment by questionpython** [comment]
https://github.com/avramit/Instahack/issues/30

**Comment by NAZSSYKO** [comment]
Thanks you but this problem come

**Comment by avramit** [comment]
Fixed in the new version

**Comment by madafumaddy** [comment]
For proxybroker error I install setupkit and install python-dev and unroll got the error fix but got error with proxt as mentioned above

**Comment by madafumaddy** [comment]
from ._cfficore import *                       ModuleNotFoundError: No module named 'pycares._cfficore'                                              $ pip install pycares                              Requirement already satisfied: pycares in /data/data/com.termux/files/usr/lib/python3.6/site-packag

**Comment by madafumaddy** [comment]
mportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/_core.cpython-36m.so"...                              
During handling of the above exception, another exception occurred:                                   
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>            from proxybroker import Broker
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/__init__.py", line 28, in <module>                                           from .proxy import Proxy  # noqa
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/proxy.py", line 11, in <module>
    from .resolver import Resolver
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/proxybroker/resolver.py", line 8, in <module>
    import aiodns                                    File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/aiodns/__init__.py", line 7, in <module>                                                 import pycares                                   File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pycares/__init__.py", line 7, in <module>

**Comment by ehsanbehzai** [comment]
Hi iam ehsan my problem is...please help me
Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by xHackxhackx** [comment]
Hi, I'm using termux terminal and my problem is :(Traceback (most recent call last):
  File "hackinsta.py", line 154, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'). Can someone help me? ._.
