### ISSUE TITLE
Cool project, looking forward to improvement in proxy changing

### ISSUE THREAD

**Issue by derrickyin** [avramit/instahack#3]
Please add an opinion letting us input a proxylist.txt so the request will not be blocked after few tries! Thanks m8!

**Comment by avramit** [comment]
thx, i add proxy support

**Comment by derrickyin** [comment]
Cool! Looking forward to see your next update

**Comment by derrickyin** [comment]
By the way, will there be any error if I change the delay time to < 1 sec?

**Comment by derrickyin** [comment]
Some Error occurs though.

requests.exceptions.ProxyError: HTTPConnectionPool(host='89.38.147.233', port=80): Max retries exceeded with url: http://myexternalip.com/raw (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1034b3048>: Failed to establish a new connection: [Errno 61] Connection refused',)))

**Comment by avramit** [comment]
@derrickyin yes, you cant do it. its dangerous, you need a delay between the Attempts

**Comment by avramit** [comment]
@derrickyin  i know that error, its broken proxy

**Comment by avramit** [comment]
@derrickyin remove "95.142.37.157" from the list

**Comment by derrickyin** [comment]
@avramit It fails even if I generate a new proxy.txt list

**Comment by derrickyin** [comment]
Some suggestion: Can you do something like "when a proxy is not working/max. attempts have been reached, change it to another proxy in the proxy list?
Dunno whether it works.

**Comment by avramit** [comment]
@derrickyin, yes. it's working i do it when you suggest to add proxy.
(the proxy was in my to-do list but... i have tests and that..)
*.sorry for my English.*

**Comment by avramit** [comment]
@derrickyin please choose proxy only from Torvpn proxy list

**Comment by derrickyin** [comment]
Ya it's cool! thanks man!

**Comment by avramit** [comment]
@derrickyin if you have more idea, share me, i will do it
