### ISSUE TITLE
Old version instahack class bug (self) (Old version)

### ISSUE THREAD

**Issue by g14m3** [avramit/Instahack#30]
File "hackinsta.py", line 128, in Login
    randomProxy() #Check that, may contain bugs
NameError: name 'randomProxy' is not defined

**Comment by questionpython** [comment]
Hey ,
go to hackinsta.py file and edit this.
change
```
				print ('[$] Try to use proxy after fail.')
```
to
```
				print ('[$] Try to use proxy after fail.')
				self.randomProxy() #Check that, may contain bugs
```
and enjoy. :+1:

**Comment by g14m3** [comment]
Thx bro

**Comment by avramit** [comment]
Please download the new code
