### ISSUE TITLE
Something Missing?

### ISSUE THREAD

**Issue by ae3583** [avramit/Instahack#35]
![screenshot_20180223-142632](https://user-images.githubusercontent.com/36776024/36616499-d0395fa6-1898-11e8-8b5c-3b5028fdeb12.png)
 I keep getting this error.
What am I doing wrong? 

I'm using Termux on Honor 6x running EMUI 5.0 (Android 7.0)

**Comment by avramit** [comment]
First thing, run this on the computer, It will be better.
Second thing., You need to install modules

**Comment by SinghAmitoz** [comment]
Sir can you please tell me 
where to do these things on computer???

**Comment by ae3583** [comment]
Makes sense. Alright, can you point me in the direction of the modules? Also can I do this from the CMD console, or do I need something else? I've not done this before, and I'm doing this to help someone else.

**Comment by avramit** [comment]
@SinghAmitoz install python and run the file (Look at youtube how to that)
@ae3583 You can do that from any shell (Cmd, Terminal) install the moudles from readme file

**Comment by ae3583** [comment]
Alright. Thank you.
