### ISSUE TITLE
Module proxybroker not found

### ISSUE THREAD

**Issue by SinghAmitoz** [avramit/Instahack#37]
![screenshot_20180224-223447](https://user-images.githubusercontent.com/29795746/36632939-0e0b3550-19b3-11e8-9c75-c25d5cf7e943.png)
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
I am using termux on my android

**Comment by avramit** [comment]
Please install the moudle
```pip install proxybroker```

**Comment by ae3583** [comment]
Actually ran into this issue on my end, it'd be better to just do it from computer like avramit told me. Even after fixing that, it just lead to my issue.

**Comment by SinghAmitoz** [comment]
I install the module but it is showing that complie failed with error 1
![screenshot_20180224-224722](https://user-images.githubusercontent.com/29795746/36633074-f45cd9b8-19b4-11e8-92aa-d126f9ef871b.png)

**Comment by avramit** [comment]
Please close this issue, I already said that you need to install the script on the pc

**Comment by SinghAmitoz** [comment]
Ok thank you
