### ISSUE TITLE
proxy.txt file is needed I think .. pls help

### ISSUE THREAD

**Issue by Spotify2000** [avramit/Instahack#38]
File "hackinsta.py", line 108
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax

Pls help..

**Comment by avramit** [comment]
You dont need a proxy file! i rewrite the code to find a proxy automatically (not finish yet)

**Comment by Spotify2000** [comment]
How to unauthorized the thread ?

**Comment by avramit** [comment]
@Spotify2000 what?

**Comment by Spotify2000** [comment]
What is the solution for now to solve this?

**Comment by avramit** [comment]
Do what i'm wrote in https://github.com/avramit/Instahack/issues/36
