### ISSUE TITLE
Pleas answer me -  socks module not found

### ISSUE THREAD

**Issue by kemaafa** [avramit/Instahack#42]
instahack
$ cd instahack
$ ls
README.md     passwords.txt  screenshot.png
hackinsta.py  proxy.txt      toolss
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 7, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'

**Comment by avramit** [comment]
you need to install "PySocks"
```pip install PySocks``` 
read the readme file

**Comment by LazFireLaix** [comment]
Ok I did what you said and this happened 



python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
$


Please help me

**Comment by ShubhamShukla29** [comment]
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
$ pip install proxtbreaker
Collecting proxtbreaker
  Could not find a version that satisfies the requirement proxtbreaker (from versions: )
No matching distribution found for proxtbreaker

Help me!

**Comment by rohitbiruli008** [comment]
I, also stucked​ in same problem, help.
