### ISSUE TITLE
Proxybroker can not installed - Android

### ISSUE THREAD

**Issue by adrathod40** [avramit/Instahack#45]
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-h2w6zcn7/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-id5_y92d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-h2w6zcn7/pycares/

**Comment by avramit** [comment]
What platform are use?

**Comment by googial** [comment]
Same happening with me now

**Comment by avramit** [comment]
@googial Which os do you use?

**Comment by googial** [comment]
I am using android 7.0 custom ROM

**Comment by adrathod40** [comment]
I also use android.

**Comment by avramit** [comment]
@googial @adrathod40 please try to run your pc

**Comment by erick08** [comment]
I can not do the pip install proxybroker to fix the traceback error line 10

when I try to install it appears:


Command ´´/data/data/com.termux/files/urs/bin/python =u-c ´´import setuptools, tokenize;_file_=´
/data/data/com.termux/files/usr/tmp/pip=build=4fpumpvq/pycares/setup.py´;f=getattr( tokenize, ´open´
, open)(_file_);code=f.read().replace(´\r\n´);f.close();exec(compile(code,_file_, ´exec))´´ install --record /data/data/com.termux/files/usr/tmp/pip-96nh6wyp-record/install-record.txt --single-version-externally-managed --compile´´ failed with error code 1 in data/data/com.termux/files/usr/tmp/pip-build-4fpumpvq/pycares/

Before this message appears also:


error: command `arm-linux-androideabi-clang´ failed with exit status 1

If you can help me, I thank you.

**Comment by MetalMaster999** [comment]
Me too. I tried to install proxybroker to my Android phone by saying pip install proxybroker. It started installing but gave me 

error: command `arm-linux-androideabi-clang´ failed with exit status 1

Followed by a red error text. So since I couldn't install proxybroker, my instahacker won't work too. Would appreciate some help. Thank you.

**Comment by mohammadaliazizkhani** [comment]
mee too. 
please help

**Comment by harsh266** [comment]
Facing same problem...pls help

**Comment by erick08** [comment]
@harsh266
@mohammadaliazizkhani
@vshlkshk

Use this: git clone
https://github.com/fuck3erboy/instahack.git
