### ISSUE TITLE
Help - Android

### ISSUE THREAD

**Issue by OLIVERQI** [avramit/Instahack#46]
ERORE :
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-8g7o8awr/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-7fblo7a1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-8g7o8awr/pycares/

**Comment by avramit** [comment]
With which os are you trying to run the script?

**Comment by avramit** [comment]
Please see: https://github.com/avramit/Instahack/issues/45
