### ISSUE TITLE
Error - Module import

### ISSUE THREAD

**Issue by NexifyUS** [avramit/Instahack#5]
root@kali:~# cd Desktop
root@kali:~/Desktop# git clone https://github.com/avramit/instahack.git
Cloning into 'instahack'...
remote: Counting objects: 70, done.
remote: Total 70 (delta 0), reused 0 (delta 0), pack-reused 70
Unpacking objects: 100% (70/70), done.
root@kali:~/Desktop# cd instahack
root@kali:~/Desktop/instahack# ls
hackinsta.py  pass.txt  proxy.txt  README.md  screenshot.jpg
**root@kali:~/Desktop/instahack# python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 1, in <module>
    import requests
ImportError: No module named requests**
root@kali:~/Desktop/instahack#

**Comment by avramit** [comment]
you need to install "requests" library.
Command in the shell "pip install requests"

**Comment by avramit** [comment]
Please install the new code and close the issue

**Comment by rezsoltani** [comment]
Hi I am reza 
ls                                         README.md       passwords.txt                hackinsta.py    screenshot.png
$ python hackinsta.py                        Traceback (most recent call last):             File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker           ModuleNotFoundError: No module named 'proxybroker'

**Comment by avramit** [comment]
@rezsoltani please install "proxybroker"
```pip install proxybroker```

**Comment by thiago025** [comment]
@avramit
$ pip install proxybroker
Collecting proxybroker
  Using cached proxybroker-0.3.1-py3-none-any.whl
Requirement already satisfied: maxminddb==1.3.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Requirement already satisfied: aiohttp==3.0.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Requirement already satisfied: async-timeout==2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Collecting aiodns==1.1.1 (from proxybroker)
  Using cached aiodns-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: multidict<5.0,>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: idna-ssl>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Collecting pycares>=1.0.0 (from aiodns==1.1.1->proxybroker)
  Using cached pycares-2.3.0.tar.gz
Requirement already satisfied: idna>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.0.1->proxybroker)
Installing collected packages: pycares, aiodns, proxybroker
  Running setup.py install for pycares ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-06_7_ajh/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-txevyuh4-record/install-record.txt --single-version-externally-managed --compile:
running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/pycares
    copying pycares/__init__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/__main__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/errno.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/_version.py -> build/lib.linux-armv7l-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    creating build/temp.linux-armv7l-3.6/deps
    creating build/temp.linux-armv7l-3.6/deps/c-ares
    creating build/temp.linux-armv7l-3.6/deps/c-ares/src
    arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data
/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-armv7l-3.6/src/pycares.o
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-06_7_ajh/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-txevyuh4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-06_7_ajh/pycares/

**Comment by shubhambahri** [comment]
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;file='/data/data/com.termux/files/usr/tmp/pip-build-06_7_ajh/pycares/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-txevyuh4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-06_7_ajh/pycares/$ python hackinsta.py Traceback (most recent call last): File "hackinsta.py", line 10, in 
from proxybroker import Broker ModuleNotFoundError: No module named 'proxybroker'

**Comment by unknownseccode** [comment]
@rezasoltani
git clone https://github.com/P13RC33/instahack
Use that 👍

**Comment by meso6666meso** [comment]
$ python hackinsta.py
python: can't open file 'hackinsta.py': [Errno 2] No such file or directory
$ pip install requests
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.6/site-packages (2.18.4)
Requirement already satisfied: idna<2.7,>=2.5 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from requests) (1.22)

**Comment by user385** [comment]
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'
$ pip install proxybroker
Collecting proxybroker
  Using cached https://files.pythonhosted.org/packages/b8/46/e6f85d49cd9982cde7722aabc760d2a540fd2f1141ca3d3e967012306a1b/proxybroker-0.3.1-py3-none-any.whl
Requirement already satisfied: async-timeout==2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (2.0.0)
Requirement already satisfied: maxminddb==1.3.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (1.3.0)
Requirement already satisfied: aiohttp==3.0.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (3.0.1)
Collecting aiodns==1.1.1 (from proxybroker)
  Using cached https://files.pythonhosted.org/packages/bd/f5/b69cb930fd5ab0569396659afe3f3c0d37d4098e5d0ba6afdf6fd9388cb0/aiodns-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: attrs>=17.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (17.4.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (4.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (1.1.1)
Requirement already satisfied: idna-ssl>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (1.0.1)
Collecting pycares>=1.0.0 (from aiodns==1.1.1->proxybroker)
  Using cached https://files.pythonhosted.org/packages/89/5c/3a7e1a52d6abb52b9ca1a56d2df699936e89d8b98f75cfd60d03363e7c10/pycares-2.3.0.tar.gz
Requirement already satisfied: idna>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.0.1->proxybroker) (2.6)
Installing collected packages: pycares, aiodns, proxybroker
  Running setup.py install for pycares ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-81qmbexp/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-5lzehos0/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/pycares
    copying pycares/__init__.py -> build/lib.linux-aarch64-3.6/pycares
    copying pycares/__main__.py -> build/lib.linux-aarch64-3.6/pycares
    copying pycares/errno.py -> build/lib.linux-aarch64-3.6/pycares
    copying pycares/_version.py -> build/lib.linux-aarch64-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-aarch64-3.6
    creating build/temp.linux-aarch64-3.6/src
    creating build/temp.linux-aarch64-3.6/deps
    creating build/temp.linux-aarch64-3.6/deps/c-ares
    creating build/temp.linux-aarch64-3.6/deps/c-ares/src
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Oz -Oz -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-aarch64-3.6/src/pycares.o
    In file included from src/pycares.c:2:
    src/pycares.h:7:10: fatal error: 'Python.h' file not found
    #include "Python.h"
             ^~~~~~~~~~
    1 error generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-81qmbexp/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-5lzehos0/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-81qmbexp/pycares/

**Comment by mostwantedha** [comment]
hey guys i have any problem in installing proxybroker:

pip install proxybroker
Collecting proxybroker
  Using cached https://files.pythonhosted.org/packages/22/01/19acc197b3f772619a56d18c1be6ff0f8b0fa1698941a8ad9870dcbe8283/proxybroker-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in proxybroker setup command: package_data must be a dictionary mapping package names to lists of wildcard patterns
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Sx0DEI/proxybroker/

**Comment by ShubhamShukla29** [comment]
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker

**Comment by ShubhamShukla29** [comment]
$ python2 hackinsta.py
  File "hackinsta.py", line 54
    async def proxything(proxies):
            ^
SyntaxError: invalid syntax
