### ISSUE TITLE
How to start ? (i am noob)

### ISSUE THREAD

**Issue by DrBright301** [avramit/Instahack#55]
I'm sorry to ask this but I want to use your code but I don't know where to start? If you could respond and give me an explanation it would be greatly appreciated.

**Comment by QuerttyCode** [comment]
Bruh you mines well not even do this if you cant understand the code

**Comment by DrBright301** [comment]
@QuerttyCode Well i want to tweak it to see what each piece does. The way i learn is by dissection and experimenting. I can't learn through reading about coding:\

**Comment by QuerttyCode** [comment]
I learned raw and started watching videos on youtube i picked up on it fast so my advise is youtube

**Comment by DrBright301** [comment]
@QuerttyCode Thing is I don't know how to run it. I'm new to GitHub so i don't know the way things work here.

**Comment by avramit** [comment]
Please look at https://github.com/avramit/Instahack/issues/67
I explained how to do all
