### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by vj-vijay7** [avramit/Instahack#58]
When I type Python hackinsta.py
It says
Module not found error: No module named 'socks'

**Comment by dungeon-master69** [comment]
Pip install Pysocks

**Comment by vj-vijay7** [comment]
Thank you so much. After typing that I get another error import
proxybroker. Please help me.. i tried pressing pip install proxybroker but
there was an error. I have attached that.

**Comment by avramit** [comment]
Please install all the modules from the readme file!!!

**Comment by skSpawN** [comment]
hello 
im install all the modules
but i get another error about proxybroker
i install it but in end
i get a 1 error

**Comment by Akriosss47** [comment]
same proxybroken error

**Comment by cbiswash0** [comment]
i also face this proxybroker problem..please,anyone help..
