### ISSUE TITLE
Proxy broker error 

### ISSUE THREAD

**Issue by Pratham2004** [avramit/Instahack#62]
(https://github.com/avramit/Instahack/blob/84b343b7074dfde572090aa9bc1f645fc64a4b80/hackinsta.py#L10)
$ python hackinsta.py
Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'

**Comment by newhavbsb** [comment]
What to do in that case

**Comment by AnonymousTTA** [comment]
Don't the problem is not your termux/terminal is because the author need to update it that's it :)

**Comment by AnonymousTTA** [comment]
Worry*

**Comment by dungeon-master69** [comment]
I have same errror please help me

**Comment by sahab123** [comment]
I have the same error

**Comment by skyrimmax55** [comment]
Hi I have Problem when I want to hack insta I have this error ModuleNotFoundError: No module named 'proxybroker' pls helpe how can I fixd it

**Comment by newhavbsb** [comment]
Even I have the same prblem

**Comment by jappanrana** [comment]
Same problem

**Comment by avramit** [comment]
you need to install the proxybroker module!

**Comment by MrCreepy04** [comment]
Make pip install proxybroker than it works

**Comment by jappanrana** [comment]
Not working still I used command
Pip install proxybroker then

**Comment by Nima9Faraji** [comment]
same problem !
and i can't install proxybroker
i used "pip install proxybroker" then i got lot error !

**Comment by A-Zabarjad** [comment]
same issue...Helpp

**Comment by DanTheTechMan1** [comment]
Same promblem , has anyone found a fix to it?
