### ISSUE TITLE
How to run on pc.. 

### ISSUE THREAD

**Issue by Socialstar111** [avramit/Instahack#67]
Sir please let me know how to run it on pc..i have to download any software?

**Comment by avramit** [comment]
First step: Please install the last python version from https://www.python.org/downloads/
if you are using windows make sure you add the python to the "PATH" (in the setup settings)

Second step:
open the terminal (command prompt) and run this command:
```
pip install argparse requests PySocks asyncio proxybroke
```
the command will install the required modules.

Third step:
open the terminal and write this:
```
python instabrute.py USERNAME PASSWORD_FILE
```
that line will run the python file, please change the "USERNAME"  to the account username and "PASSWORD_FILE" to the path of the passwords file
