### ISSUE TITLE
Python 2.7 input error (Old version) #2

### ISSUE THREAD

**Issue by dunkelite** [avramit/Instahack#7]
Hello there! Why I am receiving this error? whats wrong? Please help :(

_______________________________________________________________________________________________________________

4 Passwords loads successfully
Please enter a username: imnotjsph

Traceback (most recent call last):
  File "C:\Users\dunke\Downloads\Compressed\instahack-master\hackinsta.py", line 100, in <module>
    username = str(input('Please enter a username: '))
  File "<string>", line 1, in <module>
NameError: name 'imnotjsph' is not defined

**Comment by avramit** [comment]
Fixed
