### ISSUE TITLE
Pip install proxy breaker

### ISSUE THREAD

**Issue by Driny** [avramit/Instahack#76]
IT says 
Could not find a version that satisfies the requirement proxybreaker (from versions: )
No matching distribution found for proxybreaker
Please help me someone what to do

**Comment by Driny** [comment]
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-9vwjy6ny/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-ntmmbohq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-9vwjy6ny/pycares/
THis appears when i write pip install (all modules here). 
Please help

**Comment by blkrt** [comment]
I had this issue some days ago so I updated python to last version after that I could install proxybreaker :)

**Comment by Driny** [comment]
Thank you so i should only upgrade to Python3 then it will work . Thanks a
lot

**Comment by CoryTDC** [comment]
update to python3.6 and python3.6-pip

**Comment by ahxanhaxhmi** [comment]
its had still that issue now its saying erroe with python setup.py and not install proxy breaker

**Comment by ahxanhaxhmi** [comment]
still there is a problm its saying error in setup.py and cant install proxy
broker

**Comment by mehranmeshki** [comment]
This is error
Could not find a version that satisfies the requirement setuptools (from versions: )
No matching distribution found for setuptoolsl
