### ISSUE TITLE
Problem in proxybroker

### ISSUE THREAD

**Issue by erick08** [avramit/Instahack#85]
I can not install Proxybroker to fix:

Traceback (most recent call last):
  File "hackinsta.py", line 10, in <module>
    from proxybroker import Broker
ModuleNotFoundError: No module named 'proxybroker'

When I try to install, this appears:

$ pip install proxybroker
Collecting proxybroker
  Using cached proxybroker-0.3.1-py3-none-any.whl
Requirement already satisfied: maxminddb==1.3.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Collecting aiodns==1.1.1 (from proxybroker)
  Using cached aiodns-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: async-timeout==2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Requirement already satisfied: aiohttp==3.0.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker)
Collecting pycares>=1.0.0 (from aiodns==1.1.1->proxybroker)
  Using cached pycares-2.3.0.tar.gz
Requirement already satisfied: attrs>=17.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: multidict<5.0,>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: idna-ssl>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker)
Requirement already satisfied: idna>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.0.1->proxybroker)
Installing collected packages: pycares, aiodns, proxybroker
  Running setup.py install for pycares ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-mbjj8xfa-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/pycares
    copying pycares/__init__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/__main__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/errno.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/_version.py -> build/lib.linux-armv7l-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    creating build/temp.linux-armv7l-3.6/deps
    creating build/temp.linux-armv7l-3.6/deps/c-ares
    creating build/temp.linux-armv7l-3.6/deps/c-ares/src
    arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-armv7l-3.6/src/pycares.o
    In file included from src/pycares.c:2:
    In file included from src/pycares.h:7:
    /data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error: 'crypt.h' file not found
    #include <crypt.h>
             ^~~~~~~~~
    1 error generated.
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-mbjj8xfa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-5tpo61wy/pycares/

If you can help me, I appreciate it.

**Comment by erick08** [comment]
@avramit

**Comment by giriraj039** [comment]
im also facing the same problem

**Comment by erick08** [comment]
$ pip install proxybroker
Collecting proxybroker
  Downloading https://files.pythonhosted.org/packages/b8/46/e6f85d49cd9982cde7722aabc760d2a540fd2f1141ca3d3e967012306a1b/proxybroker-0.3.1-py3-none-any.whl (1.6MB)
    0% |▏                               | 10kB 2.4M    1% |▍                               | 20kB 501k    1% |▋                               | 30kB 395k    2% |▉                               | 40kB 422k    3% |█                               | 51kB 480k    3% |█▎                              | 61kB 568k    4% |█▌                              | 71kB 554k    5% |█▊                              | 81kB 502k    5% |█▉                              | 92kB 556k    6% |██                              | 102kB 608    7% |██▎                             | 112kB 619    7% |██▌                             | 122kB 572    8% |██▊                             | 133kB 612    9% |███                             | 143kB 683    9% |███▏                            | 153kB 691    10% |███▍                            | 163kB 68    11% |███▌                            | 174kB 79    11% |███▊                            | 184kB 77    12% |████                            | 194kB 76    13% |████▏                           | 204kB 74    13% |████▍                           | 215kB 70    14% |████▋                           | 225kB 1.    15% |████▉                           | 235kB 1.    15% |█████                           | 245kB 1.    16% |█████▎                          | 256kB 1.    16% |█████▍                          | 266kB 95    17% |█████▋                          | 276kB 95    18% |█████▉                          | 286kB 98    18% |██████                          | 296kB 96    19% |██████▎                         | 307kB 1.    20% |██████▌                         | 317kB 1.    20% |██████▊                         | 327kB 90    21% |███████                         | 337kB 87    22% |███████                         | 348kB 86    22% |███████▎                        | 358kB 89    23% |███████▌                        | 368kB 96    24% |███████▊                        | 378kB 84    24% |████████                        | 389kB 1.    25% |████████▏                       | 399kB 1.    26% |████████▍                       | 409kB 1.    26% |████████▋                       | 419kB 89    27% |████████▊                       | 430kB 1.    28% |█████████                       | 440kB 1.    28% |█████████▏                      | 450kB 94    29% |█████████▍                      | 460kB 91    30% |█████████▋                      | 471kB 98    30% |█████████▉                      | 481kB 1.    31% |██████████                      | 491kB 99    31% |██████████▎                     | 501kB 86    32% |██████████▌                     | 512kB 92    33% |██████████▋                     | 522kB 1.    33% |██████████▉                     | 532kB 87    34% |███████████                     | 542kB 88    35% |███████████▎                    | 552kB 1.    35% |███████████▌                    | 563kB 1.    36% |███████████▊                    | 573kB 1.    37% |████████████                    | 583kB 1.    37% |████████████▏                   | 593kB 1.    38% |████████████▎                   | 604kB 1.    39% |████████████▌                   | 614kB 1.    39% |████████████▊                   | 624kB 1.    40% |█████████████                   | 634kB 1.    41% |█████████████▏                  | 645kB 1.    41% |█████████████▍                  | 655kB 1.    42% |█████████████▋                  | 665kB 1.    43% |█████████████▉                  | 675kB 1.    43% |██████████████                  | 686kB 1.    44% |██████████████▏                 | 696kB 1.    45% |██████████████▍                 | 706kB 1.    45% |██████████████▋                 | 716kB 1.    46% |██████████████▉                 | 727kB 1.    47% |███████████████                 | 737kB 1.    47% |███████████████▎                | 747kB 1.    48% |███████████████▌                | 757kB 1.    48% |███████████████▊                | 768kB 1.    49% |███████████████▉                | 778kB 1.    50% |████████████████                | 788kB 1.    50% |████████████████▎               | 798kB 1.    51% |████████████████▌               | 808kB 1.    52% |████████████████▊               | 819kB 1.    52% |█████████████████               | 829kB 1.    53% |█████████████████▏              | 839kB 1.    54% |█████████████████▍              | 849kB 1.    54% |█████████████████▌              | 860kB 1.    55% |█████████████████▊              | 870kB 1.    56% |██████████████████              | 880kB 1.    56% |██████████████████▏             | 890kB 1.    57% |██████████████████▍             | 901kB 1.    58% |██████████████████▋             | 911kB 1.    58% |██████████████████▉             | 921kB 1.    59% |███████████████████             | 931kB 1.    60% |███████████████████▏            | 942kB 1.    60% |███████████████████▍            | 952kB 1.    61% |███████████████████▋            | 962kB 1.    62% |███████████████████▉            | 972kB 1.    62% |████████████████████            | 983kB 1.    63% |████████████████████▎           | 993kB 1.    63% |████████████████████▌           | 1.0MB 1.    64% |████████████████████▊           | 1.0MB 1.    65% |█████████████████████           | 1.0MB 1.    65% |█████████████████████           | 1.0MB 1.    66% |█████████████████████▎          | 1.0MB 1.    67% |█████████████████████▌          | 1.1MB 1.    67% |█████████████████████▊          | 1.1MB 1.    68% |██████████████████████          | 1.1MB 1.    69% |██████████████████████▏         | 1.1MB 1.    69% |██████████████████████▍         | 1.1MB 1.    70% |██████████████████████▋         | 1.1MB 1.    71% |██████████████████████▊         | 1.1MB 1.    71% |███████████████████████         | 1.1MB 1.    72% |███████████████████████▏        | 1.1MB 1.    73% |███████████████████████▍        | 1.1MB 1.    73% |███████████████████████▋        | 1.2MB 1.    74% |███████████████████████▉        | 1.2MB 1.    75% |████████████████████████        | 1.2MB 1.    75% |████████████████████████▎       | 1.2MB 1.    76% |████████████████████████▍       | 1.2MB 1.    77% |████████████████████████▋       | 1.2MB 1.    77% |████████████████████████▉       | 1.2MB 1.    78% |█████████████████████████       | 1.2MB 1.    78% |█████████████████████████▎      | 1.2MB 1.    79% |█████████████████████████▌      | 1.2MB 1.    80% |█████████████████████████▊      | 1.3MB 1.    80% |██████████████████████████      | 1.3MB 1.    81% |██████████████████████████▏     | 1.3MB 1.    82% |██████████████████████████▎     | 1.3MB 1.    82% |██████████████████████████▌     | 1.3MB 1.    83% |██████████████████████████▊     | 1.3MB 1.    84% |███████████████████████████     | 1.3MB 1.    84% |███████████████████████████▏    | 1.3MB 1.    85% |███████████████████████████▍    | 1.3MB 1.    86% |███████████████████████████▋    | 1.4MB 1.    86% |███████████████████████████▉    | 1.4MB 1.    87% |████████████████████████████    | 1.4MB 1.    88% |████████████████████████████▏   | 1.4MB 1.    88% |████████████████████████████▍   | 1.4MB 1.    89% |████████████████████████████▋   | 1.4MB 1.    90% |████████████████████████████▉   | 1.4MB 1.    90% |█████████████████████████████   | 1.4MB 1.    91% |█████████████████████████████▎  | 1.4MB 1.    92% |█████████████████████████████▌  | 1.4MB 1.    92% |█████████████████████████████▋  | 1.5MB 1.    93% |█████████████████████████████▉  | 1.5MB 1.    94% |██████████████████████████████  | 1.5MB 1.    94% |██████████████████████████████▎ | 1.5MB 1.    95% |██████████████████████████████▌ | 1.5MB 1.    95% |██████████████████████████████▊ | 1.5MB 1.    96% |███████████████████████████████ | 1.5MB 1.    97% |███████████████████████████████▏| 1.5MB 1.    97% |███████████████████████████████▍| 1.5MB 1.    98% |███████████████████████████████▌| 1.5MB 1.    99% |███████████████████████████████▊| 1.6MB 1.    99% |████████████████████████████████| 1.6MB 1.    100% |████████████████████████████████| 1.6MB 1.2MB/s
Requirement already satisfied: aiodns==1.1.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages/aiodns-1.1.1-py3.6.egg (from proxybroker) (1.1.1)
Requirement already satisfied: async-timeout==2.0.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (2.0.0)
Requirement already satisfied: maxminddb==1.3.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (1.3.0)
Requirement already satisfied: aiohttp==3.0.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from proxybroker) (3.0.1)
Collecting pycares>=1.0.0 (from aiodns==1.1.1->proxybroker)
  Downloading https://files.pythonhosted.org/packages/89/5c/3a7e1a52d6abb52b9ca1a56d2df699936e89d8b98f75cfd60d03363e7c10/pycares-2.3.0.tar.gz (224kB)
    4% |█▌                              | 10kB 3.3M    9% |███                             | 20kB 3.7M    13% |████▍                           | 30kB 3.8    18% |█████▉                          | 40kB 3.9    22% |███████▎                        | 51kB 3.9    27% |████████▊                       | 61kB 4.2    31% |██████████▏                     | 71kB 4.3    36% |███████████▋                    | 81kB 1.7    40% |█████████████                   | 92kB 1.9    45% |██████████████▋                 | 102kB 1.    50% |████████████████                | 112kB 1.    54% |█████████████████▌              | 122kB 1.    59% |███████████████████             | 133kB 1.    63% |████████████████████▍           | 143kB 1.    68% |█████████████████████▉          | 153kB 92    72% |███████████████████████▎        | 163kB 91    77% |████████████████████████▊       | 174kB 91    81% |██████████████████████████▏     | 184kB 1.    86% |███████████████████████████▊    | 194kB 1.    91% |█████████████████████████████▏  | 204kB 1.    95% |██████████████████████████████▋ | 215kB 1.    100% |████████████████████████████████| 225kB 1.3MB/s
Requirement already satisfied: attrs>=17.4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (17.4.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (4.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (1.1.1)
Requirement already satisfied: idna-ssl>=1.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from aiohttp==3.0.1->proxybroker) (1.0.1)
Requirement already satisfied: idna>=2.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from yarl<2.0,>=1.0->aiohttp==3.0.1->proxybroker) (2.6)
Installing collected packages: proxybroker, pycares
  Running setup.py install for pycares ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-_fbhw9xp/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-t5sfu94_/install-record.txt --single-version-externally-managed --compile:
running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.6
    creating build/lib.linux-armv7l-3.6/pycares
    copying pycares/__init__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/__main__.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/errno.py -> build/lib.linux-armv7l-3.6/pycares
    copying pycares/_version.py -> build/lib.linux-armv7l-3.6/pycares
    running build_ext
    building 'pycares._core' extension
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    creating build/temp.linux-armv7l-3.6/deps
    creating build/temp.linux-armv7l-3.6/deps/c-ares
    creating build/temp.linux-armv7l-3.6/deps/c-ares/src
    arm-linux-androideabi-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Os -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/data/data/com.termux/files/usr/include/python3.6m -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c src/pycares.c -o build/temp.linux-armv7l-3.6/src/pycares.o
    unable to execute 'arm-linux-androideabi-clang': No such file or directory
    error: command 'arm-linux-androideabi-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-_fbhw9xp/pycares/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-t5sfu94_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-_fbhw9xp/pycares/

**Comment by erick08** [comment]
Use this: git clone
https://github.com/fuck3erboy/instahack.git

**Comment by ivy6poison** [comment]
@erick08 
Have you decide this problem????
